// PROVIDER CONTRACT VERIFICATION — tracking-service proves it satisfies the consumer pact.
//
// The pact file was generated by order-service's consumer test (trackingClient.pact.ts).
// This test replays every interaction in that file against the REAL tracking-service
// and checks that actual responses match what order-service declared it expects.
//
// No order-service code runs here. The tracking-service team runs this independently.
//
// What this catches: tracking-service breaking a contract the consumer depends on —
//   e.g. renaming a field, dropping a field, changing a status code.

process.env.DATABASE_URL =
  "postgresql://tracking_user:tracking_pass@localhost:5435/tracking_test_db";

import path from "path";
import { Verifier } from "@pact-foundation/pact";
import app from "../../src/app";
import prisma from "../../src/lib/prisma";
import { Server } from "http";

const PORT = 3101;
let server: Server;

beforeAll(async () => {
  await prisma.$connect();
  server = app.listen(PORT);
});

afterAll(async () => {
  await prisma.$disconnect();
  server.close();
});

describe("tracking-service — Pact provider verification", () => {
  it("satisfies the order-service consumer pact", async () => {
    await new Verifier({
      provider: "tracking-service",
      providerBaseUrl: `http://localhost:${PORT}`,
      pactUrls: [
        path.resolve(
          __dirname,
          "../../../pacts/order-service-tracking-service.json"
        ),
      ],
      // State handlers — called before each interaction to set up DB state
      stateHandlers: {
        "no existing tracking records": async () => {
          await prisma.trackingRecord.deleteMany();
        },
      },
      logLevel: "warn",
    }).verifyProvider();
  });
});
